# Generated by Django 3.2.9 on 2022-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
