# Generated by Django 3.2.9 on 2022-06-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='t_name',
        ),
    ]
