# Generated by Django 3.2.9 on 2022-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20220612_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
