# Generated by Django 3.2.9 on 2022-06-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20220613_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
    ]
