# Generated by Django 3.2.9 on 2022-06-13 17:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_alter_task_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
