# Generated by Django 3.2.9 on 2022-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0018_alter_task_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateField(default=None),
        ),
    ]
