# Generated by Django 3.2.9 on 2022-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0019_task_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED'), ('in-progress', 'IN-PROGRESS'), ('hold', 'HOLD'), ('black', 'BLACK')], default='open', max_length=20),
        ),
    ]
